baseURL = 'https://plasmawind.github.io/'
languageCode = 'en-us'
title = 'plasmawind'
theme = 'archie'
copyright = '© plasmawind'

pygmentsstyle = 'monokai'
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
favicon="https://plasmawind.github.io/images/favicon.png"

paginate = 3

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "<sub><sup>*tech and more...*</sup></sub>"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

[[params.social]]
name = 'Github'
icon = 'github'
url = "https://www.github.com/plasmawind"

[[menu.main]]
name = "All Posts"
url = "/posts"
weight = 1
